on:
  push:
    branches: 
      - '*'
name: Backend Container workflows

jobs:
    run-backend-unit-tests:
        runs-on: ubuntu-latest
        env:
          working-directory: ./back
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v2
          - run: npm run test

    build-and-deploy-backend-container:
        needs: run-backend-unit-tests
        runs-on: ubuntu-latest
        env:
          working-directory: ./back
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v2
          
          - name: 'Login via Azure CLI'
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: 'Build and push image'
            uses: azure/docker-login@v1
            with:
              login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}
          - run: |
              docker build ${{ env.working-directory }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/memelord_api
              docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/memelord_api